# Generated by Django 2.2.5 on 2020-02-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200204_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couresresource',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursetag',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='courses',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course/%Y/%m', verbose_name='封面图'),
        ),
    ]
