# Generated by Django 2.2.5 on 2020-02-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_index',
            field=models.BooleanField(default=False, verbose_name='是否首页推荐'),
        ),
    ]
