# Generated by Django 2.2.5 on 2020-02-09 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20200109_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('image', models.ImageField(max_length=300, upload_to='banner/%Y/%m', verbose_name='图片')),
                ('url', models.URLField(max_length=300, verbose_name='URL')),
                ('index', models.IntegerField(default=0, verbose_name='顺序')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
    ]
