# Generated by Django 2.2.5 on 2020-01-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200128_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
