# Generated by Django 2.2.5 on 2020-02-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200128_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='is_index',
            field=models.BooleanField(default=False, verbose_name='是否首页展示'),
        ),
    ]
